name: Unity Project Build
on:
- push
jobs:
  test:
    name: Unity Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
        - StandaloneWindows64
        - StandaloneLinux64
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: NuGet install
      run: pushd unity/Assets && nuget install && popd
        #      - name: Unity runner
        #        uses: game-ci/unity-test-runner@v2
        #        env:
        #          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        #        with:
        #          projectPath: unity
        #          githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Build project
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: unity
        buildName: joyrtc-unity
        targetPlatform: ${{ matrix.targetPlatform }}
    - name: Upload to artifact
      uses: actions/upload-artifact@v3
      with:
        name: JoyRTC-Unity-${{ matrix.targetPlatform }}
        path: build/${{ matrix.targetPlatform }}

